version: '3.5'

services:
  nodebb:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 127.0.0.1:4567:4567
    volumes:
      - nodebb-config:/etc/nodebb

  db:
    image: mongo:6.0
    restart: unless-stopped
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo:/data/db
      - type: bind
        source: ./init_user.js
        target: /docker-entrypoint-initdb.d/init_user.js

volumes:
  nodebb-config:
  mongo:
